# -*- coding: utf-8 -*-
"""yolov5 custom object detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZMo3n6os_F9BYs95n2Vylh4LOPbS7BT
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt  # install

import torch
import utils
display = utils.notebook_init()  # checks

!unzip -q ../dataset.zip -d ../  # unzip

# Train YOLOv5s on custom dataset
!python train.py --img 640 --batch 16 --epochs 10 --data /content/yolov5/data/dataset.yaml --weights yolov5s.pt --cache

!python detect.py --weights runs/train/exp/weights/best.pt --img 640 --conf 0.10 --source ../dataset/val/images